
[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
WARNING: jaxlib 0.4.28 does not provide the extra 'cuda12'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.19.1 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.3 which is incompatible.
orbax-checkpoint 0.11.25 requires jax>=0.6.0, but you have jax 0.4.28 which is incompatible.
equinox 0.13.0 requires jax>=0.4.38, but you have jax 0.4.28 which is incompatible.
distrax 0.1.7 requires jax>=0.7.0, but you have jax 0.4.28 which is incompatible.
distrax 0.1.7 requires jaxlib>=0.7.0, but you have jaxlib 0.4.28 which is incompatible.
optax 0.2.6 requires jax>=0.5.3, but you have jax 0.4.28 which is incompatible.
optax 0.2.6 requires jaxlib>=0.5.3, but you have jaxlib 0.4.28 which is incompatible.
chex 0.1.91 requires jax>=0.7.0, but you have jax 0.4.28 which is incompatible.
chex 0.1.91 requires jaxlib>=0.7.0, but you have jaxlib 0.4.28 which is incompatible.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
2025-09-30 19:54:52.042733: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1759254892.058119 2826056 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1759254892.063253 2826056 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1759254892.077239 2826056 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1759254892.077286 2826056 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1759254892.077293 2826056 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1759254892.077298 2826056 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/cluster/work/sebasrb/ksim-gym-example/train.py", line 14, in <module>
    import ksim
  File "/cluster/home/sebasrb/.local/lib/python3.11/site-packages/ksim/__init__.py", line 5, in <module>
    from .actuators import *
  File "/cluster/home/sebasrb/.local/lib/python3.11/site-packages/ksim/actuators.py", line 20, in <module>
    from ksim.types import Metadata, PhysicsData, PhysicsModel
  File "/cluster/home/sebasrb/.local/lib/python3.11/site-packages/ksim/types.py", line 37, in <module>
    @jax.tree_util.register_dataclass
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: register_dataclass() missing 2 required positional arguments: 'data_fields' and 'meta_fields'
